spring:
  rabbitmq:
    #host: 127.0.0.1
    host: 39.104.173.57 # 阿里云服务器
    port: 5672          # 不配置的话默认也是5672
    virtual-host: /     # 不配置的话默认也是/
    username: guest
    password: guest
    #listener:
    #  direct:
    #    acknowledge-mode: manual # manual none 默认是auto 在Listener中结合channel完成手动ACK。
    # confirm/return 还需要配置RabbitTemplate
    #publisher-confirm-type: simple # confirm
    #publisher-returns: true # return
  application:
    admin: test-messaging
  cloud:
    stream:
      binders: # 配置绑定的rabbitmq服务信息
        defaultRabbit:  # 用于binding整合
          type: rabbit  # 消息组件类型
          environment:  # 设置RabbitMQ相关的信息
            spring:
              rabbitmq:
                host: 39.104.173.57 # 阿里云服务器
                port: 5672          # 不配置的话默认也是5672
                virtual-host: /     # 不配置的话默认也是/
                username: guest
                password: guest
      bindings: # 服务的整合处理
        output: # 这是一个通道的名称
          destination: studyExchange # liuyang.exchange.topic # 貌似用已存在的有点问题
          #consumer:
          #  exchangeType: topic # The exchange type: direct, fanout, headers or topic for non-partitioned destinations and direct, headers or topic for partitioned destinations.
          #  bindingRoutingKey: liuyang.q
          content-type: application/json
          binder: defaultRabbit # 设置要绑定的消息服务
        input:  # 这是一个通道的名字
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
